#include "var_monitor.hpp"
#include <iostream>
#include <cmath>
#include <csignal>
#include <atomic>
#include <thread>
#include <chrono>
#include <random>
#include <mutex>

static std::atomic<bool> g_running{true};

void signal_handler(int) { g_running = false; }

int main() {
    std::signal(SIGINT, signal_handler);
    std::signal(SIGTERM, signal_handler);

    double sine_wave = 0.0;
    double cosine_wave = 0.0;
    double temperature = 20.0;
    double pressure = 1013.25;
    double humidity = 45.0;
    int32_t counter = 0;
    bool flag = false;
    double setpoint = 50.0;
    double pid_kp = 1.5;
    double pid_ki = 0.2;
    double pid_kd = 0.05;
    double pid_output = 0.0;
    double pos_x = 0.0;
    double pos_y = 0.0;
    double vel_x = 0.0;
    double vel_y = 0.0;

    // Array estático: lectura Y escritura por indice desde el monitor
    double spectrum[32] = {};

    // Vector + mutex: lectura Y escritura por indice desde el monitor
    std::vector<double> sensor_bank(8, 0.0);
    std::mutex sensor_bank_mtx;

    // Array con getter custom: SOLO lectura (no se puede escribir desde el monitor)
    double internal_buf[16] = {};
    std::mutex internal_mtx;

    varmon::VarMonitor monitor;

    monitor.register_var("waves.sine", &sine_wave);
    monitor.register_var("waves.cosine", &cosine_wave);
    monitor.register_var("sensors.temperature", &temperature);
    monitor.register_var("sensors.pressure", &pressure);
    monitor.register_var("sensors.humidity", &humidity);
    monitor.register_var("system.counter", &counter);
    monitor.register_var("system.flag", &flag);
    monitor.register_var("control.setpoint", &setpoint);
    monitor.register_var("control.pid.kp", &pid_kp);
    monitor.register_var("control.pid.ki", &pid_ki);
    monitor.register_var("control.pid.kd", &pid_kd);
    monitor.register_var("control.pid.output", &pid_output);
    monitor.register_var("state.position.x", &pos_x);
    monitor.register_var("state.position.y", &pos_y);
    monitor.register_var("state.velocity.x", &vel_x);
    monitor.register_var("state.velocity.y", &vel_y);
    monitor.register_var("5waves.sine", &sine_wave);
    monitor.register_var("5waves.cosine", &cosine_wave);
    monitor.register_var("5sensors.temperature", &temperature);
    monitor.register_var("5sensors.pressure", &pressure);
    monitor.register_var("5sensors.humidity", &humidity);
    monitor.register_var("5system.counter", &counter);
    monitor.register_var("5system.flag", &flag);
    monitor.register_var("5control.setpoint", &setpoint);
    monitor.register_var("5control.pid.kp", &pid_kp);
    monitor.register_var("5control.pid.ki", &pid_ki);
    monitor.register_var("5control.pid.kd", &pid_kd);
    monitor.register_var("5control.pid.output", &pid_output);
    monitor.register_var("5state.position.x", &pos_x);
    monitor.register_var("5state.position.y", &pos_y);
    monitor.register_var("5state.velocity.x", &vel_x);
    monitor.register_var("5state.velocity.y", &vel_y);
    monitor.register_var("4waves.sine", &sine_wave);
    monitor.register_var("4waves.cosine", &cosine_wave);
    monitor.register_var("4sensors.temperature", &temperature);
    monitor.register_var("4sensors.pressure", &pressure);
    monitor.register_var("4sensors.humidity", &humidity);
    monitor.register_var("4system.counter", &counter);
    monitor.register_var("4system.flag", &flag);
    monitor.register_var("4control.setpoint", &setpoint);
    monitor.register_var("4control.pid.kp", &pid_kp);
    monitor.register_var("4control.pid.ki", &pid_ki);
    monitor.register_var("4control.pid.kd", &pid_kd);
    monitor.register_var("4control.pid.output", &pid_output);
    monitor.register_var("4state.position.x", &pos_x);
    monitor.register_var("4state.position.y", &pos_y);
    monitor.register_var("4state.velocity.x", &vel_x);
    monitor.register_var("4state.velocity.y", &vel_y);
    monitor.register_var("3waves.sine", &sine_wave);
    monitor.register_var("3waves.cosine", &cosine_wave);
    monitor.register_var("3sensors.temperature", &temperature);
    monitor.register_var("3sensors.pressure", &pressure);
    monitor.register_var("3sensors.humidity", &humidity);
    monitor.register_var("3system.counter", &counter);
    monitor.register_var("3system.flag", &flag);
    monitor.register_var("3control.setpoint", &setpoint);
    monitor.register_var("3control.pid.kp", &pid_kp);
    monitor.register_var("3control.pid.ki", &pid_ki);
    monitor.register_var("3control.pid.kd", &pid_kd);
    monitor.register_var("3control.pid.output", &pid_output);
    monitor.register_var("3state.position.x", &pos_x);
    monitor.register_var("3state.position.y", &pos_y);
    monitor.register_var("3state.velocity.x", &vel_x);
    monitor.register_var("3state.velocity.y", &vel_y);
    monitor.register_var("2waves.sine", &sine_wave);
    monitor.register_var("2waves.cosine", &cosine_wave);
    monitor.register_var("2sensors.temperature", &temperature);
    monitor.register_var("2sensors.pressure", &pressure);
    monitor.register_var("2sensors.humidity", &humidity);
    monitor.register_var("2system.counter", &counter);
    monitor.register_var("2system.flag", &flag);
    monitor.register_var("2control.setpoint", &setpoint);
    monitor.register_var("2control.pid.kp", &pid_kp);
    monitor.register_var("2control.pid.ki", &pid_ki);
    monitor.register_var("2control.pid.kd", &pid_kd);
    monitor.register_var("2control.pid.output", &pid_output);
    monitor.register_var("2state.position.x", &pos_x);
    monitor.register_var("2state.position.y", &pos_y);
    monitor.register_var("2state.velocity.x", &vel_x);
    monitor.register_var("2state.velocity.y", &vel_y);
    monitor.register_var("1waves.sine", &sine_wave);
    monitor.register_var("1waves.cosine", &cosine_wave);
    monitor.register_var("1sensors.temperature", &temperature);
    monitor.register_var("1sensors.pressure", &pressure);
    monitor.register_var("1sensors.humidity", &humidity);
    monitor.register_var("1system.counter", &counter);
    monitor.register_var("1system.flag", &flag);
    monitor.register_var("1control.setpoint", &setpoint);
    monitor.register_var("1control.pid.kp", &pid_kp);
    monitor.register_var("1control.pid.ki", &pid_ki);
    monitor.register_var("1control.pid.kd", &pid_kd);
    monitor.register_var("1control.pid.output", &pid_output);
    monitor.register_var("1state.position.x", &pos_x);
    monitor.register_var("1state.position.y", &pos_y);
    monitor.register_var("1state.velocity.x", &vel_x);
    monitor.register_var("1state.velocity.y", &vel_y); 
    monitor.register_var("4waves.sine", &sine_wave);
    monitor.register_var("4waves.cosine", &cosine_wave);
    monitor.register_var("4sensors.temperature", &temperature);
    monitor.register_var("4sensors.pressure", &pressure);
    monitor.register_var("4sensors.humidity", &humidity);
    monitor.register_var("4system.counter", &counter);
    monitor.register_var("4system.flag", &flag);
    monitor.register_var("4control.setpoint", &setpoint);
    monitor.register_var("4control.pid.kp", &pid_kp);
    monitor.register_var("4control.pid.ki", &pid_ki);
    monitor.register_var("4control.pid.kd", &pid_kd);
    monitor.register_var("4control.pid.output", &pid_output);
    monitor.register_var("4state.position.x", &pos_x);
    monitor.register_var("4state.position.y", &pos_y);
    monitor.register_var("4state.velocity.x", &vel_x);
    monitor.register_var("4state.velocity.y", &vel_y);
    monitor.register_var("45waves.sine", &sine_wave);
    monitor.register_var("45waves.cosine", &cosine_wave);
    monitor.register_var("45sensors.temperature", &temperature);
    monitor.register_var("45sensors.pressure", &pressure);
    monitor.register_var("45sensors.humidity", &humidity);
    monitor.register_var("45system.counter", &counter);
    monitor.register_var("45system.flag", &flag);
    monitor.register_var("45control.setpoint", &setpoint);
    monitor.register_var("45control.pid.kp", &pid_kp);
    monitor.register_var("45control.pid.ki", &pid_ki);
    monitor.register_var("45control.pid.kd", &pid_kd);
    monitor.register_var("45control.pid.output", &pid_output);
    monitor.register_var("45state.position.x", &pos_x);
    monitor.register_var("45state.position.y", &pos_y);
    monitor.register_var("45state.velocity.x", &vel_x);
    monitor.register_var("45state.velocity.y", &vel_y);
    monitor.register_var("44waves.sine", &sine_wave);
    monitor.register_var("44waves.cosine", &cosine_wave);
    monitor.register_var("44sensors.temperature", &temperature);
    monitor.register_var("44sensors.pressure", &pressure);
    monitor.register_var("44sensors.humidity", &humidity);
    monitor.register_var("44system.counter", &counter);
    monitor.register_var("44system.flag", &flag);
    monitor.register_var("44control.setpoint", &setpoint);
    monitor.register_var("44control.pid.kp", &pid_kp);
    monitor.register_var("44control.pid.ki", &pid_ki);
    monitor.register_var("44control.pid.kd", &pid_kd);
    monitor.register_var("44control.pid.output", &pid_output);
    monitor.register_var("44state.position.x", &pos_x);
    monitor.register_var("44state.position.y", &pos_y);
    monitor.register_var("44state.velocity.x", &vel_x);
    monitor.register_var("44state.velocity.y", &vel_y);
    monitor.register_var("43waves.sine", &sine_wave);
    monitor.register_var("43waves.cosine", &cosine_wave);
    monitor.register_var("43sensors.temperature", &temperature);
    monitor.register_var("43sensors.pressure", &pressure);
    monitor.register_var("43sensors.humidity", &humidity);
    monitor.register_var("43system.counter", &counter);
    monitor.register_var("43system.flag", &flag);
    monitor.register_var("43control.setpoint", &setpoint);
    monitor.register_var("43control.pid.kp", &pid_kp);
    monitor.register_var("43control.pid.ki", &pid_ki);
    monitor.register_var("43control.pid.kd", &pid_kd);
    monitor.register_var("43control.pid.output", &pid_output);
    monitor.register_var("43state.position.x", &pos_x);
    monitor.register_var("43state.position.y", &pos_y);
    monitor.register_var("43state.velocity.x", &vel_x);
    monitor.register_var("43state.velocity.y", &vel_y);
    monitor.register_var("42waves.sine", &sine_wave);
    monitor.register_var("42waves.cosine", &cosine_wave);
    monitor.register_var("42sensors.temperature", &temperature);
    monitor.register_var("42sensors.pressure", &pressure);
    monitor.register_var("42sensors.humidity", &humidity);
    monitor.register_var("42system.counter", &counter);
    monitor.register_var("42system.flag", &flag);
    monitor.register_var("42control.setpoint", &setpoint);
    monitor.register_var("42control.pid.kp", &pid_kp);
    monitor.register_var("42control.pid.ki", &pid_ki);
    monitor.register_var("42control.pid.kd", &pid_kd);
    monitor.register_var("42control.pid.output", &pid_output);
    monitor.register_var("42state.position.x", &pos_x);
    monitor.register_var("42state.position.y", &pos_y);
    monitor.register_var("42state.velocity.x", &vel_x);
    monitor.register_var("42state.velocity.y", &vel_y);
    monitor.register_var("41waves.sine", &sine_wave);
    monitor.register_var("41waves.cosine", &cosine_wave);
    monitor.register_var("41sensors.temperature", &temperature);
    monitor.register_var("41sensors.pressure", &pressure);
    monitor.register_var("41sensors.humidity", &humidity);
    monitor.register_var("41system.counter", &counter);
    monitor.register_var("41system.flag", &flag);
    monitor.register_var("41control.setpoint", &setpoint);
    monitor.register_var("41control.pid.kp", &pid_kp);
    monitor.register_var("41control.pid.ki", &pid_ki);
    monitor.register_var("41control.pid.kd", &pid_kd);
    monitor.register_var("41control.pid.output", &pid_output);
    monitor.register_var("41state.position.x", &pos_x);
    monitor.register_var("41state.position.y", &pos_y);
    monitor.register_var("41state.velocity.x", &vel_x);
    monitor.register_var("41state.velocity.y", &vel_y); 
    monitor.register_var("3waves.sine", &sine_wave);
    monitor.register_var("3waves.cosine", &cosine_wave);
    monitor.register_var("3sensors.temperature", &temperature);
    monitor.register_var("3sensors.pressure", &pressure);
    monitor.register_var("3sensors.humidity", &humidity);
    monitor.register_var("3system.counter", &counter);
    monitor.register_var("3system.flag", &flag);
    monitor.register_var("3control.setpoint", &setpoint);
    monitor.register_var("3control.pid.kp", &pid_kp);
    monitor.register_var("3control.pid.ki", &pid_ki);
    monitor.register_var("3control.pid.kd", &pid_kd);
    monitor.register_var("3control.pid.output", &pid_output);
    monitor.register_var("3state.position.x", &pos_x);
    monitor.register_var("3state.position.y", &pos_y);
    monitor.register_var("3state.velocity.x", &vel_x);
    monitor.register_var("3state.velocity.y", &vel_y);
    monitor.register_var("35waves.sine", &sine_wave);
    monitor.register_var("35waves.cosine", &cosine_wave);
    monitor.register_var("35sensors.temperature", &temperature);
    monitor.register_var("35sensors.pressure", &pressure);
    monitor.register_var("35sensors.humidity", &humidity);
    monitor.register_var("35system.counter", &counter);
    monitor.register_var("35system.flag", &flag);
    monitor.register_var("35control.setpoint", &setpoint);
    monitor.register_var("35control.pid.kp", &pid_kp);
    monitor.register_var("35control.pid.ki", &pid_ki);
    monitor.register_var("35control.pid.kd", &pid_kd);
    monitor.register_var("35control.pid.output", &pid_output);
    monitor.register_var("35state.position.x", &pos_x);
    monitor.register_var("35state.position.y", &pos_y);
    monitor.register_var("35state.velocity.x", &vel_x);
    monitor.register_var("35state.velocity.y", &vel_y);
    monitor.register_var("34waves.sine", &sine_wave);
    monitor.register_var("34waves.cosine", &cosine_wave);
    monitor.register_var("34sensors.temperature", &temperature);
    monitor.register_var("34sensors.pressure", &pressure);
    monitor.register_var("34sensors.humidity", &humidity);
    monitor.register_var("34system.counter", &counter);
    monitor.register_var("34system.flag", &flag);
    monitor.register_var("34control.setpoint", &setpoint);
    monitor.register_var("34control.pid.kp", &pid_kp);
    monitor.register_var("34control.pid.ki", &pid_ki);
    monitor.register_var("34control.pid.kd", &pid_kd);
    monitor.register_var("34control.pid.output", &pid_output);
    monitor.register_var("34state.position.x", &pos_x);
    monitor.register_var("34state.position.y", &pos_y);
    monitor.register_var("34state.velocity.x", &vel_x);
    monitor.register_var("34state.velocity.y", &vel_y);
    monitor.register_var("33waves.sine", &sine_wave);
    monitor.register_var("33waves.cosine", &cosine_wave);
    monitor.register_var("33sensors.temperature", &temperature);
    monitor.register_var("33sensors.pressure", &pressure);
    monitor.register_var("33sensors.humidity", &humidity);
    monitor.register_var("33system.counter", &counter);
    monitor.register_var("33system.flag", &flag);
    monitor.register_var("33control.setpoint", &setpoint);
    monitor.register_var("33control.pid.kp", &pid_kp);
    monitor.register_var("33control.pid.ki", &pid_ki);
    monitor.register_var("33control.pid.kd", &pid_kd);
    monitor.register_var("33control.pid.output", &pid_output);
    monitor.register_var("33state.position.x", &pos_x);
    monitor.register_var("33state.position.y", &pos_y);
    monitor.register_var("33state.velocity.x", &vel_x);
    monitor.register_var("33state.velocity.y", &vel_y);
    monitor.register_var("32waves.sine", &sine_wave);
    monitor.register_var("32waves.cosine", &cosine_wave);
    monitor.register_var("32sensors.temperature", &temperature);
    monitor.register_var("32sensors.pressure", &pressure);
    monitor.register_var("32sensors.humidity", &humidity);
    monitor.register_var("32system.counter", &counter);
    monitor.register_var("32system.flag", &flag);
    monitor.register_var("32control.setpoint", &setpoint);
    monitor.register_var("32control.pid.kp", &pid_kp);
    monitor.register_var("32control.pid.ki", &pid_ki);
    monitor.register_var("32control.pid.kd", &pid_kd);
    monitor.register_var("32control.pid.output", &pid_output);
    monitor.register_var("32state.position.x", &pos_x);
    monitor.register_var("32state.position.y", &pos_y);
    monitor.register_var("32state.velocity.x", &vel_x);
    monitor.register_var("32state.velocity.y", &vel_y);
    monitor.register_var("31waves.sine", &sine_wave);
    monitor.register_var("31waves.cosine", &cosine_wave);
    monitor.register_var("31sensors.temperature", &temperature);
    monitor.register_var("31sensors.pressure", &pressure);
    monitor.register_var("31sensors.humidity", &humidity);
    monitor.register_var("31system.counter", &counter);
    monitor.register_var("31system.flag", &flag);
    monitor.register_var("31control.setpoint", &setpoint);
    monitor.register_var("31control.pid.kp", &pid_kp);
    monitor.register_var("31control.pid.ki", &pid_ki);
    monitor.register_var("31control.pid.kd", &pid_kd);
    monitor.register_var("31control.pid.output", &pid_output);
    monitor.register_var("31state.position.x", &pos_x);
    monitor.register_var("31state.position.y", &pos_y);
    monitor.register_var("31state.velocity.x", &vel_x);
    monitor.register_var("31state.velocity.y", &vel_y);
    monitor.register_var("2waves.sine", &sine_wave);
    monitor.register_var("2waves.cosine", &cosine_wave);
    monitor.register_var("2sensors.temperature", &temperature);
    monitor.register_var("2sensors.pressure", &pressure);
    monitor.register_var("2sensors.humidity", &humidity);
    monitor.register_var("2system.counter", &counter);
    monitor.register_var("2system.flag", &flag);
    monitor.register_var("2control.setpoint", &setpoint);
    monitor.register_var("2control.pid.kp", &pid_kp);
    monitor.register_var("2control.pid.ki", &pid_ki);
    monitor.register_var("2control.pid.kd", &pid_kd);
    monitor.register_var("2control.pid.output", &pid_output);
    monitor.register_var("2state.position.x", &pos_x);
    monitor.register_var("2state.position.y", &pos_y);
    monitor.register_var("2state.velocity.x", &vel_x);
    monitor.register_var("2state.velocity.y", &vel_y);
    monitor.register_var("25waves.sine", &sine_wave);
    monitor.register_var("25waves.cosine", &cosine_wave);
    monitor.register_var("25sensors.temperature", &temperature);
    monitor.register_var("25sensors.pressure", &pressure);
    monitor.register_var("25sensors.humidity", &humidity);
    monitor.register_var("25system.counter", &counter);
    monitor.register_var("25system.flag", &flag);
    monitor.register_var("25control.setpoint", &setpoint);
    monitor.register_var("25control.pid.kp", &pid_kp);
    monitor.register_var("25control.pid.ki", &pid_ki);
    monitor.register_var("25control.pid.kd", &pid_kd);
    monitor.register_var("25control.pid.output", &pid_output);
    monitor.register_var("25state.position.x", &pos_x);
    monitor.register_var("25state.position.y", &pos_y);
    monitor.register_var("25state.velocity.x", &vel_x);
    monitor.register_var("25state.velocity.y", &vel_y);
    monitor.register_var("24waves.sine", &sine_wave);
    monitor.register_var("24waves.cosine", &cosine_wave);
    monitor.register_var("24sensors.temperature", &temperature);
    monitor.register_var("24sensors.pressure", &pressure);
    monitor.register_var("24sensors.humidity", &humidity);
    monitor.register_var("24system.counter", &counter);
    monitor.register_var("24system.flag", &flag);
    monitor.register_var("24control.setpoint", &setpoint);
    monitor.register_var("24control.pid.kp", &pid_kp);
    monitor.register_var("24control.pid.ki", &pid_ki);
    monitor.register_var("24control.pid.kd", &pid_kd);
    monitor.register_var("24control.pid.output", &pid_output);
    monitor.register_var("24state.position.x", &pos_x);
    monitor.register_var("24state.position.y", &pos_y);
    monitor.register_var("24state.velocity.x", &vel_x);
    monitor.register_var("24state.velocity.y", &vel_y);
    monitor.register_var("23waves.sine", &sine_wave);
    monitor.register_var("23waves.cosine", &cosine_wave);
    monitor.register_var("23sensors.temperature", &temperature);
    monitor.register_var("23sensors.pressure", &pressure);
    monitor.register_var("23sensors.humidity", &humidity);
    monitor.register_var("23system.counter", &counter);
    monitor.register_var("23system.flag", &flag);
    monitor.register_var("23control.setpoint", &setpoint);
    monitor.register_var("23control.pid.kp", &pid_kp);
    monitor.register_var("23control.pid.ki", &pid_ki);
    monitor.register_var("23control.pid.kd", &pid_kd);
    monitor.register_var("23control.pid.output", &pid_output);
    monitor.register_var("23state.position.x", &pos_x);
    monitor.register_var("23state.position.y", &pos_y);
    monitor.register_var("23state.velocity.x", &vel_x);
    monitor.register_var("23state.velocity.y", &vel_y);
    monitor.register_var("22waves.sine", &sine_wave);
    monitor.register_var("22waves.cosine", &cosine_wave);
    monitor.register_var("22sensors.temperature", &temperature);
    monitor.register_var("22sensors.pressure", &pressure);
    monitor.register_var("22sensors.humidity", &humidity);
    monitor.register_var("22system.counter", &counter);
    monitor.register_var("22system.flag", &flag);
    monitor.register_var("22control.setpoint", &setpoint);
    monitor.register_var("22control.pid.kp", &pid_kp);
    monitor.register_var("22control.pid.ki", &pid_ki);
    monitor.register_var("22control.pid.kd", &pid_kd);
    monitor.register_var("22control.pid.output", &pid_output);
    monitor.register_var("22state.position.x", &pos_x);
    monitor.register_var("22state.position.y", &pos_y);
    monitor.register_var("22state.velocity.x", &vel_x);
    monitor.register_var("22state.velocity.y", &vel_y);
    monitor.register_var("21waves.sine", &sine_wave);
    monitor.register_var("21waves.cosine", &cosine_wave);
    monitor.register_var("21sensors.temperature", &temperature);
    monitor.register_var("21sensors.pressure", &pressure);
    monitor.register_var("21sensors.humidity", &humidity);
    monitor.register_var("21system.counter", &counter);
    monitor.register_var("21system.flag", &flag);
    monitor.register_var("21control.setpoint", &setpoint);
    monitor.register_var("21control.pid.kp", &pid_kp);
    monitor.register_var("21control.pid.ki", &pid_ki);
    monitor.register_var("21control.pid.kd", &pid_kd);
    monitor.register_var("21control.pid.output", &pid_output);
    monitor.register_var("21state.position.x", &pos_x);
    monitor.register_var("21state.position.y", &pos_y);
    monitor.register_var("21state.velocity.x", &vel_x);
    monitor.register_var("21state.velocity.y", &vel_y);
    monitor.register_var("1waves.sine", &sine_wave);
    monitor.register_var("1waves.cosine", &cosine_wave);
    monitor.register_var("1sensors.temperature", &temperature);
    monitor.register_var("1sensors.pressure", &pressure);
    monitor.register_var("1sensors.humidity", &humidity);
    monitor.register_var("1system.counter", &counter);
    monitor.register_var("1system.flag", &flag);
    monitor.register_var("1control.setpoint", &setpoint);
    monitor.register_var("1control.pid.kp", &pid_kp);
    monitor.register_var("1control.pid.ki", &pid_ki);
    monitor.register_var("1control.pid.kd", &pid_kd);
    monitor.register_var("1control.pid.output", &pid_output);
    monitor.register_var("1state.position.x", &pos_x);
    monitor.register_var("1state.position.y", &pos_y);
    monitor.register_var("1state.velocity.x", &vel_x);
    monitor.register_var("1state.velocity.y", &vel_y);
    monitor.register_var("15waves.sine", &sine_wave);
    monitor.register_var("15waves.cosine", &cosine_wave);
    monitor.register_var("15sensors.temperature", &temperature);
    monitor.register_var("15sensors.pressure", &pressure);
    monitor.register_var("15sensors.humidity", &humidity);
    monitor.register_var("15system.counter", &counter);
    monitor.register_var("15system.flag", &flag);
    monitor.register_var("15control.setpoint", &setpoint);
    monitor.register_var("15control.pid.kp", &pid_kp);
    monitor.register_var("15control.pid.ki", &pid_ki);
    monitor.register_var("15control.pid.kd", &pid_kd);
    monitor.register_var("15control.pid.output", &pid_output);
    monitor.register_var("15state.position.x", &pos_x);
    monitor.register_var("15state.position.y", &pos_y);
    monitor.register_var("15state.velocity.x", &vel_x);
    monitor.register_var("15state.velocity.y", &vel_y);
    monitor.register_var("14waves.sine", &sine_wave);
    monitor.register_var("14waves.cosine", &cosine_wave);
    monitor.register_var("14sensors.temperature", &temperature);
    monitor.register_var("14sensors.pressure", &pressure);
    monitor.register_var("14sensors.humidity", &humidity);
    monitor.register_var("14system.counter", &counter);
    monitor.register_var("14system.flag", &flag);
    monitor.register_var("14control.setpoint", &setpoint);
    monitor.register_var("14control.pid.kp", &pid_kp);
    monitor.register_var("14control.pid.ki", &pid_ki);
    monitor.register_var("14control.pid.kd", &pid_kd);
    monitor.register_var("14control.pid.output", &pid_output);
    monitor.register_var("14state.position.x", &pos_x);
    monitor.register_var("14state.position.y", &pos_y);
    monitor.register_var("14state.velocity.x", &vel_x);
    monitor.register_var("14state.velocity.y", &vel_y);
    monitor.register_var("13waves.sine", &sine_wave);
    monitor.register_var("13waves.cosine", &cosine_wave);
    monitor.register_var("13sensors.temperature", &temperature);
    monitor.register_var("13sensors.pressure", &pressure);
    monitor.register_var("13sensors.humidity", &humidity);
    monitor.register_var("13system.counter", &counter);
    monitor.register_var("13system.flag", &flag);
    monitor.register_var("13control.setpoint", &setpoint);
    monitor.register_var("13control.pid.kp", &pid_kp);
    monitor.register_var("13control.pid.ki", &pid_ki);
    monitor.register_var("13control.pid.kd", &pid_kd);
    monitor.register_var("13control.pid.output", &pid_output);
    monitor.register_var("13state.position.x", &pos_x);
    monitor.register_var("13state.position.y", &pos_y);
    monitor.register_var("13state.velocity.x", &vel_x);
    monitor.register_var("13state.velocity.y", &vel_y);
    monitor.register_var("12waves.sine", &sine_wave);
    monitor.register_var("12waves.cosine", &cosine_wave);
    monitor.register_var("12sensors.temperature", &temperature);
    monitor.register_var("12sensors.pressure", &pressure);
    monitor.register_var("12sensors.humidity", &humidity);
    monitor.register_var("12system.counter", &counter);
    monitor.register_var("12system.flag", &flag);
    monitor.register_var("12control.setpoint", &setpoint);
    monitor.register_var("12control.pid.kp", &pid_kp);
    monitor.register_var("12control.pid.ki", &pid_ki);
    monitor.register_var("12control.pid.kd", &pid_kd);
    monitor.register_var("12control.pid.output", &pid_output);
    monitor.register_var("12state.position.x", &pos_x);
    monitor.register_var("12state.position.y", &pos_y);
    monitor.register_var("12state.velocity.x", &vel_x);
    monitor.register_var("12state.velocity.y", &vel_y);
    monitor.register_var("11waves.sine", &sine_wave);
    monitor.register_var("11waves.cosine", &cosine_wave);
    monitor.register_var("11sensors.temperature", &temperature);
    monitor.register_var("11sensors.pressure", &pressure);
    monitor.register_var("11sensors.humidity", &humidity);
    monitor.register_var("11system.counter", &counter);
    monitor.register_var("11system.flag", &flag);
    monitor.register_var("11control.setpoint", &setpoint);
    monitor.register_var("11control.pid.kp", &pid_kp);
    monitor.register_var("11control.pid.ki", &pid_ki);
    monitor.register_var("11control.pid.kd", &pid_kd);
    monitor.register_var("11control.pid.output", &pid_output);
    monitor.register_var("11state.position.x", &pos_x);
    monitor.register_var("11state.position.y", &pos_y);
    monitor.register_var("11state.velocity.x", &vel_x);
    monitor.register_var("lorenzo", &vel_y);


    for (int i = 0; i < 5000; i++) {
        std::string name = "test" + std::to_string(i);
        monitor.register_var(name, &vel_y);
    }
    // Lectura + escritura: puntero a array C
    monitor.register_array("arrays.spectrum", spectrum, 32);

    // Lectura + escritura: vector con mutex
    monitor.register_array("arrays.sensor_bank", sensor_bank, sensor_bank_mtx);

    // Solo lectura: getter custom (devuelve copia, el monitor NO puede escribir)
    monitor.register_array("arrays.readonly_buf", [&]() -> std::vector<double> {
        std::lock_guard<std::mutex> lk(internal_mtx);
        return std::vector<double>(internal_buf, internal_buf + 16);
    });

    if (!monitor.start(10)) {
        std::cerr << "Error al iniciar VarMonitor\n";
        return 1;
    }

    std::cout << "=== Demo Server iniciado (16 escalares + 3 arrays) ===\n";
    std::cout << "Presiona Ctrl+C para salir\n\n";

    std::mt19937 rng(42);
    std::normal_distribution<double> noise(0.0, 0.5);
    double t = 0.0;

    while (g_running) {
        sine_wave = std::sin(t);
        cosine_wave = std::cos(t);
        temperature = 20.0 + 5.0 * std::sin(t * 0.1) + noise(rng);
        pressure = 1013.25 + 2.0 * std::sin(t * 0.05) + noise(rng) * 0.3;
        humidity = 45.0 + 10.0 * std::sin(t * 0.03) + noise(rng) * 0.5;
        counter++;
        flag = (counter % 20) < 10;
        pid_output = pid_kp * sine_wave + pid_ki * t * 0.001 + pid_kd * cosine_wave;
        pos_x = 10.0 * std::sin(t * 0.2);
        pos_y = 10.0 * std::cos(t * 0.2);
        vel_x = 2.0 * std::cos(t * 0.2);
        vel_y = -2.0 * std::sin(t * 0.2);

        for (int i = 0; i < 4; i++)
            spectrum[i] = std::sin(t * (i + 1) * 0.3) * (32 - i) / 32.0;

        {
            std::lock_guard<std::mutex> lock(sensor_bank_mtx);
            for (size_t i = 0; i < sensor_bank.size(); i++)
                sensor_bank[i] = 10.0 + 3.0 * std::sin(t * 0.5 + i * 0.8) + noise(rng) * 0.2;
        }

        {
            std::lock_guard<std::mutex> lk(internal_mtx);
            for (int i = 0; i < 16; i++)
                internal_buf[i] = std::cos(t * 0.4 + i * 0.5) * 5.0;
        }

        t += 0.01;
        monitor.write_shm_snapshot(); /* Publicar snapshot en SHM para lectores (ej. Python) */
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }

    monitor.stop();
    std::cout << "\nDemo Server detenido.\n";
    return 0;
}
